# Generated by Django 2.1.5 on 2022-03-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220322_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetype',
            options={'verbose_name_plural': 'Courses'},
        ),
    ]
